### ISSUE TITLE
INI file in Config folder

### ISSUE THREAD

**Issue by Yaron10** [RTLManager/RTLManager#7]
Hello Ezra,

Could you please save the INI file in the Config folder?
Other plugins save their files in that folder and it's more convenient. 

Thank you.
Best regards.

**Comment by ezra100** [comment]
On my system it does so, I find other plugins' INIs next to mine, there's seem to be some difference between our systems which makes the plugin to act differently on every system. Where does the plugin store the ini file on your system? The name is supposed to be `RTLManager.ini` in case you wanna search it.
Thanks
Ezra

**Comment by Yaron10** [comment]
Hello Ezra,

I use a portable NPP (i.e. I haven't installed NPP but rather downloaded the ZIP file and unzipped it).

With the first version you released `RTLManager.ini` was stored in the Config folder.
With the last version (0.2) `RTLManager.ini` is stored in the main NPP folder (i.e. with notepad++.exe etc.).
  
Thank you.
BR

**Comment by ezra100** [comment]
Check the beta, it should be fine now. Let me know if there's still any problem with that.
Thanks,
Best regards

**Comment by Yaron10** [comment]
Hello Ezra,

This is fixed. 👍 

Thank you.
BR
