### ISSUE TITLE
Add current version

### ISSUE THREAD

**Issue by Yaron10** [RTLManager/RTLManager#8]
Hello Ezra,

Could you please add the plugin's current version?

Thank you.
Best regards.

**Comment by ezra100** [comment]
Hi
Can you please tell me how to do that? I'm a bit of a newbie in this stuff.
Thanks
Ezra

**Comment by Yaron10** [comment]
Hello Ezra,

https://github.com/pnedev/compare-plugin/blob/84f216869796ee3ccb5142547b268624e0ef3190/src/Compare.rc

I think the version stored in the RC file is used by Plugin Manager.
Again, I'm not an expert. :)

Pavel Nedev (Compare Plugin developer) is currently working on a major refactoring.
I'd rather not bother him now, but If this (or anything else) doesn't work you can request his help.
Requesting Claudia's or dail's help (in the forum) might be another option.

Thank you.
BR

**Comment by ezra100** [comment]
Added version info, it will be out in the next release. Let me know if there's still any problem with that.
Thanks,
Ezra

**Comment by Yaron10** [comment]
Can you please upload the latest built DLL?

Thank you.
BR
