### ISSUE TITLE
Dialogs size 

### ISSUE THREAD

**Issue by Yaron10** [RTLManager/RTLManager#9]
Hello Ezra,

This is Compare Plugin Settings dialog:
![default](https://cloud.githubusercontent.com/assets/10229320/24981136/edfd0550-1fe3-11e7-9d49-c8f706f25f2b.png)

And this is RTLManager's:
![default](https://cloud.githubusercontent.com/assets/10229320/24981183/2fc53250-1fe4-11e7-956e-11f0d621aa5d.png)

It would be nice if you could change that.

Also, adding an ellipsis (...) to `Preferences` and `About` (in the menu) would make it look more professional. :)
  

Thank you.
Best regards.

**Comment by ezra100** [comment]
Hi
I don't sure I get what exactly do you mean I should change, do you refer to the size of the window or to the size of the font?
As for the ellipsis, I'll add that.
Thanks for the feedback, this is very helpful.
Ezra

**Comment by Yaron10** [comment]
Hello Ezra,

I was mainly referring to the font size.
But the window size could be reduced as well.

I'd suggest to have a look at Compare Plugin RC files.

Thanks for adding the ellipsis. :)

BR

**Comment by ezra100** [comment]
Took care of it, let me know if there's anything more to do.
Thanks
Ezra

**Comment by Yaron10** [comment]
Can you please upload the latest built DLL?

Thank you.
BR

**Comment by ezra100** [comment]
Just uploaded it
BR
Ezra

**Comment by Yaron10** [comment]
Hello Ezra,

Great. 👍 

Thank you.
BR
